project_id = "jyqbgqududwxhypyrkrb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
email_confirm = false

[functions.generate-chicken-coop]
verify_jwt = false

[functions.estimate-coop-price]
verify_jwt = false

[functions.request-coop-quote]
verify_jwt = true

[functions.acb-auto-topup]
verify_jwt = false

[functions.proxy-image-download]
verify_jwt = false
