// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyqbgqududwxhypyrkrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cWJncXVkdWR3eGh5cHlya3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Nzg4NjIsImV4cCI6MjA2OTM1NDg2Mn0.apfLNtDOlq33kaHCIrTJDIvTJYQDpk5JrP5Pq7B-BL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});